### ISSUE TITLE
libpangoft2

### ISSUE THREAD

**Issue by bsbhro** [Qalculate/qalculate-gtk#478]
Hi, Good morning, after upgrade my Xubuntu to 23.04 the build process fails.
"/usr/lib/x86_64-linux-gnu//libpangoft2-1.0.so.0: undefined reference to `pango_matrix_get_slant_ratio' "
'ldd' with the qalculate-gtk build (xubuntu 22.10) and the error message shows me to look in /usr/lib/x86_64-linux-gnu . Here I found:
lrwxrwxrwx    20 root 15 Dez  2022  /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so -> libpangoft2-1.0.so.0
lrwxrwxrwx    28 root 15 Dez  2022  /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 -> libpangoft2-1.0.so.0.5000.12
.rw-r--r--  104k root 15 Dez  2022  /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0.5000.12
Maybe there were other files before the upgrade. To remove the now installed library "libpangoft2-1.0-0 [1.50.12+ds-1 (lunar, now)]" isn't simple, there are many dependencies.
What to do? Many Thanks in advance!

**Comment by hanna-kn** [comment]
Did you run configure and make clean (in the qalculate-gtk build directory) after the Xubuntu upgrade?

**Comment by bsbhro** [comment]
Yes I did - and make distclean before the upgrade, after the last build.

**Comment by bsbhro** [comment]
I uninstalled libqalculate, deleted all remaining files , cloned it, built it new... The same with qalculate-gtk. The fault remains. Then I found qalculate-qt, built and installed :-) Thank you for this wonderful software! Cheers

**Comment by hanna-kn** [comment]
It is not surprising that having two different version of the same library installed in standard directories is causing issues. Because of this libqalculate is probably compiled against the include files of one version and, unsuccessfully, linked against another.
