### ISSUE TITLE
0.9.11: compile error with gcc 4.8.5

### ISSUE THREAD

**Issue by fearthebear** [Qalculate/qalculate-gtk#15]
When compiling qalculate-gtk 0.9.11 with g++-4.8.5 (openSUSE Leap 42.2), I get the following error message:

`interface.cc: In function ‘void create_main_window()’:`
`interface.cc:812:103: error: cannot pass objects of non-trivially-copyable type ‘class std::basic_string<char>’ through ‘...’`
`     gtk_list_store_insert_with_values(historystore, &history_iter, -1, 0, inhistory[i], 1, i, 4, 0, -1);`
                                                                                                       ^
`Makefile:482: recipe for target 'interface.o' failed`
`make[2]: *** [interface.o] Error 1`

I'm no programmer at all, so I googled around and got the code compiling by changing `interface.cc` line 812:
`gtk_list_store_insert_with_values(historystore, &history_iter, -1, 0, inhistory[i], 1, i, 4, 0, -1);`
to
`gtk_list_store_insert_with_values(historystore, &history_iter, -1, 0, inhistory[i].c_str(), 1, i, 4, 0, -1);`

It compiles with g++-4.8.5 and g++-6.2.1

**Comment by hanna-kn** [comment]
This issue has already been reported (#14) and fixed.
